# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E2S-gui-final.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 768)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(18, 35, 51, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 221, 51))
        self.pushButton.setStyleSheet("font: 14pt \"MS Reference Sans Serif\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(46, 173, 102, 255));")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 190, 221, 51))
        self.pushButton_2.setStyleSheet("font: 14pt \"MS Reference Sans Serif\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 120, 221, 51))
        self.pushButton_3.setStyleSheet("font: 14pt \"MS Reference Sans Serif\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(209, 91, 83, 255));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox_offered = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_offered.setGeometry(QtCore.QRect(490, 590, 261, 51))
        self.comboBox_offered.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.comboBox_offered.setObjectName("comboBox_offered")
        self.label_offered = QtWidgets.QLabel(self.centralwidget)
        self.label_offered.setGeometry(QtCore.QRect(490, 545, 251, 31))
        self.label_offered.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_offered.setObjectName("label_offered")
        self.label_subcategory = QtWidgets.QLabel(self.centralwidget)
        self.label_subcategory.setGeometry(QtCore.QRect(490, 420, 271, 41))
        self.label_subcategory.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Palatino Linotype\";")
        self.label_subcategory.setObjectName("label_subcategory")
        self.comboBox_category = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_category.setGeometry(QtCore.QRect(490, 350, 261, 51))
        self.comboBox_category.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.comboBox_category.setObjectName("comboBox_category")
        self.comboBox_subcategory = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_subcategory.setGeometry(QtCore.QRect(490, 470, 261, 51))
        self.comboBox_subcategory.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.comboBox_subcategory.setObjectName("comboBox_subcategory")
        self.label_category = QtWidgets.QLabel(self.centralwidget)
        self.label_category.setGeometry(QtCore.QRect(490, 295, 261, 41))
        self.label_category.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_category.setObjectName("label_category")
        self.doubleSpinBox_seller_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_seller_price.setGeometry(QtCore.QRect(890, 589, 261, 51))
        self.doubleSpinBox_seller_price.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.doubleSpinBox_seller_price.setMaximum(1e+16)
        self.doubleSpinBox_seller_price.setObjectName("doubleSpinBox_seller_price")
        self.doubleSpinBox_quantity = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_quantity.setGeometry(QtCore.QRect(890, 350, 261, 51))
        self.doubleSpinBox_quantity.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: rgb(255, 255, 255);\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.doubleSpinBox_quantity.setMaximum(1000000000.0)
        self.doubleSpinBox_quantity.setObjectName("doubleSpinBox_quantity")
        self.label_quantity = QtWidgets.QLabel(self.centralwidget)
        self.label_quantity.setGeometry(QtCore.QRect(900, 300, 141, 41))
        self.label_quantity.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_quantity.setObjectName("label_quantity")
        self.label_actual_price = QtWidgets.QLabel(self.centralwidget)
        self.label_actual_price.setGeometry(QtCore.QRect(900, 430, 151, 21))
        self.label_actual_price.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_actual_price.setObjectName("label_actual_price")
        self.doubleSpinBox_actual_price = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_actual_price.setGeometry(QtCore.QRect(890, 470, 261, 51))
        self.doubleSpinBox_actual_price.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.doubleSpinBox_actual_price.setMaximum(10000000000000.0)
        self.doubleSpinBox_actual_price.setObjectName("doubleSpinBox_actual_price")
        self.label_seller_price = QtWidgets.QLabel(self.centralwidget)
        self.label_seller_price.setGeometry(QtCore.QRect(890, 550, 171, 21))
        self.label_seller_price.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_seller_price.setObjectName("label_seller_price")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(319, 22, 941, 231))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(24, 43, 60, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_p_location = QtWidgets.QLabel(self.frame_2)
        self.label_p_location.setGeometry(QtCore.QRect(495, 60, 311, 151))
        self.label_p_location.setStyleSheet("font: 18pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(37, 64, 90, 255));")
        self.label_p_location.setObjectName("label_p_location")
        self.label_location = QtWidgets.QLabel(self.frame_2)
        self.label_location.setGeometry(QtCore.QRect(550, 10, 246, 41))
        self.label_location.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Sans Serif\";")
        self.label_location.setObjectName("label_location")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(500, 100, 271, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_price = QtWidgets.QLabel(self.frame_2)
        self.label_price.setGeometry(QtCore.QRect(100, 0, 239, 66))
        self.label_price.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(24, 43, 60, 255));\n"
"font: 20pt \"MS Sans Serif\";")
        self.label_price.setObjectName("label_price")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.lcdNumber.setGeometry(QtCore.QRect(50, 75, 239, 131))
        self.lcdNumber.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(37, 64, 90, 255));")
        self.lcdNumber.setDigitCount(15)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 10, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../.designer/backup/INDIAN_RUPEE_SYMBOL-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(490, 0, 55, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("glow.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 51, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ff.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frame.raise_()
        self.label_p_location.raise_()
        self.label_location.raise_()
        self.label_price.raise_()
        self.lcdNumber.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.comboBox_state = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_state.setGeometry(QtCore.QRect(90, 350, 261, 51))
        self.comboBox_state.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.comboBox_state.setObjectName("comboBox_state")
        self.label_state = QtWidgets.QLabel(self.centralwidget)
        self.label_state.setGeometry(QtCore.QRect(90, 300, 201, 41))
        self.label_state.setStyleSheet("font: 75 14pt \"Palatino Linotype\";\n"
"color: rgb(255, 255, 255);")
        self.label_state.setObjectName("label_state")
        self.comboBox_group = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_group.setGeometry(QtCore.QRect(90, 590, 261, 51))
        self.comboBox_group.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(46, 173, 102, 255));\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.comboBox_group.setObjectName("comboBox_group")
        self.label_group = QtWidgets.QLabel(self.centralwidget)
        self.label_group.setGeometry(QtCore.QRect(90, 545, 171, 31))
        self.label_group.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_group.setObjectName("label_group")
        self.comboBox_location = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_location.setGeometry(QtCore.QRect(90, 463, 261, 51))
        self.comboBox_location.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(166, 245, 106, 255));")
        self.comboBox_location.setObjectName("comboBox_location")
        self.label_location_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_location_2.setGeometry(QtCore.QRect(90, 425, 111, 31))
        self.label_location_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Palatino Linotype\";")
        self.label_location_2.setObjectName("label_location_2")
        self.comboBox_state.raise_()
        self.label_state.raise_()
        self.comboBox_group.raise_()
        self.label_group.raise_()
        self.comboBox_location.raise_()
        self.label_location_2.raise_()
        self.frame_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.comboBox_offered.raise_()
        self.label_offered.raise_()
        self.label_subcategory.raise_()
        self.comboBox_category.raise_()
        self.comboBox_subcategory.raise_()
        self.label_category.raise_()
        self.doubleSpinBox_quantity.raise_()
        self.label_quantity.raise_()
        self.label_actual_price.raise_()
        self.label_seller_price.raise_()
        self.doubleSpinBox_actual_price.raise_()
        self.doubleSpinBox_seller_price.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "PREDICT"))
        self.pushButton_3.setText(_translate("MainWindow", "RESET"))
        self.label_offered.setText(_translate("MainWindow", "Product Offered"))
        self.label_subcategory.setText(_translate("MainWindow", "Product SubCategory"))
        self.label_category.setText(_translate("MainWindow", "Product Category"))
        self.label_quantity.setText(_translate("MainWindow", "Quantity"))
        self.label_actual_price.setText(_translate("MainWindow", "Actual Price"))
        self.label_seller_price.setText(_translate("MainWindow", "Seller Price"))
        self.label_p_location.setText(_translate("MainWindow", "TextLabel"))
        self.label_location.setText(_translate("MainWindow", "Buyer Location:"))
        self.label_price.setText(_translate("MainWindow", "Buyer Price"))
        self.label_state.setText(_translate("MainWindow", "State"))
        self.label_group.setText(_translate("MainWindow", "Product Group"))
        self.label_location_2.setText(_translate("MainWindow", "Location"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
